export type ImplementedRouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ImplementedRoute {
  method: ImplementedRouteMethod;
  honoPath: string;
  snapshotFamily: "api_v1" | "flask";
  snapshotMethod?: ImplementedRouteMethod;
  snapshotPath: string;
  seedPath: string;
  routeFamily: string;
  missingResource?: {
    method: ImplementedRouteMethod;
    path: string;
    status: number;
    contentType: string;
    errorCode: string;
  };
}

export const IMPLEMENTED_ROUTES: ImplementedRoute[] = [
  {
    method: "GET",
    honoPath: "/healthz",
    snapshotFamily: "flask",
    snapshotPath: "/healthz",
    seedPath: "/healthz",
    routeFamily: "ops",
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/wiki",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki/sections/:sectionSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki/sections/<section_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki/sections/<section_slug>",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/wiki/sections/definitely-not-a-section",
      status: 404,
      contentType: "application/json",
      errorCode: "wiki_section_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki/pages/<path:page_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki/pages/<path:page_slug>",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/wiki/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "wiki_page_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/article-sources/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/article-sources/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/article-sources/search",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/article-sources/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/help",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/help",
    seedPath: "/api/v1/campaigns/<campaign_slug>/help",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/help",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/config",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/config",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/pages",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/assets",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/assets/definitely-not-an-asset.png",
      status: 404,
      contentType: "application/json",
      errorCode: "content_asset_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "content_page_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/characters",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/characters/missing-character",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/search",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/sources",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources/:sourceId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/sources/NOPE",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_source_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources/:sourceId/types/:entryType",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>/types/<entry_type>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>/types/<entry_type>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/sources/PHB/types/definitely-not-a-type",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_source_category_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/entries/:entrySlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/entries/<entry_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/entries/<entry_slug>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/entries/definitely-not-an-entry",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_entry_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/systems-monsters/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters/search",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/systems-monsters/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/live-state",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/live-state",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/live-state",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/live-state",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns",
    seedPath: "/api/v1/campaigns",
    routeFamily: "api_v1_campaigns",
  },
  {
    method: "GET",
    honoPath: "/api/v1/app",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/app",
    seedPath: "/api/v1/app",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/systems/import-runs",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/systems/import-runs",
    seedPath: "/api/v1/systems/import-runs",
    routeFamily: "api_v1_systems",
  },
  {
    method: "GET",
    honoPath: "/api/v1/systems/import-runs/:importRunId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/systems/import-runs/<int:import_run_id>",
    seedPath: "/api/v1/systems/import-runs/<int:import_run_id>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/systems/import-runs/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_import_run_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId/image",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/image",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/image",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999/image",
      status: 404,
      contentType: "application/json",
      errorCode: "session_article_image_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/logs/:sessionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/session/logs/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "session_log_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/me",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me",
    seedPath: "/api/v1/me",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/me/settings",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/settings",
    seedPath: "/api/v1/me/settings",
    routeFamily: "api_v1",
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/me/settings",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/settings",
    seedPath: "/api/v1/me/settings",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/control",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/control",
    seedPath: "/api/v1/campaigns/<campaign_slug>/control",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/control",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/control/visibility",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/control/visibility",
    seedPath: "/api/v1/campaigns/<campaign_slug>/control/visibility",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/definitely-not-a-campaign/control/visibility",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/messages",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/messages",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/messages",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/messages",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/start",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/start",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/start",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/start",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/close",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/close",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/close",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/close",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/articles",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId/reveal",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/reveal",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/reveal",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999/reveal",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/revealed",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/revealed",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/revealed",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/articles/revealed",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/logs/:sessionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/session/logs/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/config",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/config",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/assets/notes/api-sigil.txt",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/assets/definitely-not-an-asset.png",
      status: 404,
      contentType: "application/json",
      errorCode: "content_asset_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/pages/notes/api-field-report",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "content_page_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/characters/api-scout",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/characters/missing-character",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content/statblocks",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks/:statblockId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/dm-content/statblocks/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks/:statblockId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/dm-content/statblocks/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content/conditions",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions/:conditionDefinitionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/dm-content/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions/:conditionDefinitionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/dm-content/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/set-current",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/set-current",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/set-current",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/set-current",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/advance-turn",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/advance-turn",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/advance-turn",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/advance-turn",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/clear",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/clear",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/clear",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/clear",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/player-combatants",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/player-combatants",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/player-combatants",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/player-combatants",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/npc-combatants",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/npc-combatants",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/npc-combatants",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/npc-combatants",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/statblock-combatants",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/statblock-combatants",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/statblock-combatants",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/statblock-combatants",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/systems-monsters",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/systems-monsters",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/turn",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/turn",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/turn",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/turn",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/vitals",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/vitals",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/vitals",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/vitals",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/resources",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/resources",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/resources",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/resources",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/npc-resources",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/npc-resources",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/npc-resources",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/npc-resources",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/conditions",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/conditions",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/conditions",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/conditions",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/conditions/:conditionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/conditions/<int:condition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/conditions/<int:condition_id>",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/combat/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/combatants/:combatantId/player-detail-visibility",
    snapshotFamily: "flask",
    snapshotMethod: "POST",
    snapshotPath: "/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/player-detail-visibility",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/combatants/<int:combatant_id>/player-detail-visibility",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/combatants/999999/player-detail-visibility",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/conditions/:conditionId",
    snapshotFamily: "flask",
    snapshotMethod: "POST",
    snapshotPath: "/campaigns/<campaign_slug>/combat/conditions/<int:condition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/conditions/<int:condition_id>",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/combat/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/vitals",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/vitals",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/vitals",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/vitals",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/resources/:resourceId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/resources/<resource_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/resources/<resource_id>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/arden-march/session/resources/not-a-resource",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/spell-slots/:level",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/spell-slots/<int:level>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/spell-slots/<int:level>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/arden-march/session/spell-slots/99",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/inventory/:itemId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/inventory/<item_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/inventory/<item_id>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/arden-march/session/inventory/not-an-item",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-active-state",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-active-state",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-active-state",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/arden-march/session/xianxia-active-state",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/currency",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/currency",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/currency",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/currency",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/notes",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/notes",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/notes",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/notes",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/personal",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/personal",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/personal",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/personal",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/rest-preview/:restType",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/rest-preview/<rest_type>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/rest-preview/<rest_type>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/rest-preview/long",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/rest/:restType",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/rest/<rest_type>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/rest/<rest_type>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/rest/long",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/feature-states/:featureKey",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/feature-states/<feature_key>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/feature-states/<feature_key>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/feature-states/arcane-armor",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-inventory/:itemId/equipped",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>/equipped",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>/equipped",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-inventory/spirit-rice/equipped",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-inventory",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-inventory",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-inventory/:itemId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-inventory/spirit-rice",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-inventory/:itemId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-inventory/<item_id>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-inventory/spirit-rice",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/equipment/:itemId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/equipment/<item_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/equipment/<item_id>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/equipment/quarterstaff-2",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/artificer-infusions",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/artificer-infusions",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/artificer-infusions",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/artificer-infusions",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/portrait",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/portrait",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/portrait",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/portrait",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/portrait",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/portrait",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/portrait",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/portrait",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-dao-immolating-use-requests",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-dao-immolating-use-requests",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-dao-immolating-use-requests",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-dao-immolating-use-requests",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/session/xianxia-dao-immolating-use-records",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-dao-immolating-use-records",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/session/xianxia-dao-immolating-use-records",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/session/xianxia-dao-immolating-use-records",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/controls/assignment",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls/assignment",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls/assignment",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/controls/assignment",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/controls/assignment",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls/assignment",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls/assignment",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/controls/assignment",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/controls",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/controls",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/controls",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/characters",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/import/xianxia-manual",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/import/xianxia-manual",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/import/xianxia-manual",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/characters/import/xianxia-manual",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/import/xianxia-manual",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/import/xianxia-manual",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/import/xianxia-manual",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/characters/import/xianxia-manual",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/systems",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/systems",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/systems",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content/systems",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/sources",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/overrides/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/overrides/<path:entry_key>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/overrides/<path:entry_key>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/overrides/PHB:spell:mage-hand",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/custom-entries",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/custom-entries",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/custom-entries/:entrySlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/custom-entries/custom-linden-pass-scout-note",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/custom-entries/:entrySlug/archive",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>/archive",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>/archive",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/custom-entries/custom-linden-pass-scout-note/archive",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/custom-entries/:entrySlug/restore",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>/restore",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/custom-entries/<entry_slug>/restore",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/custom-entries/custom-linden-pass-scout-note/restore",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/item-mechanics/import",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/item-mechanics/import",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/item-mechanics/import",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/item-mechanics/import",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/systems/imports/dnd5e",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/systems/imports/dnd5e",
    seedPath: "/api/v1/systems/imports/dnd5e",
    routeFamily: "api_v1_systems",
  },
  {
    method: "GET",
    honoPath: "/api/v1/admin",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin",
    seedPath: "/api/v1/admin",
    routeFamily: "api_v1_admin",
  },
  {
    method: "GET",
    honoPath: "/api/v1/admin/users/:userId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>",
    seedPath: "/api/v1/admin/users/<int:user_id>",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "GET",
      path: "/api/v1/admin/users/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/sheet-edit",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/sheet-edit",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/sheet-edit",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/sheet-edit",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/membership",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/membership",
    seedPath: "/api/v1/admin/users/<int:user_id>/membership",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/membership",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/admin/users/:userId/membership",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/membership",
    seedPath: "/api/v1/admin/users/<int:user_id>/membership",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/admin/users/999999/membership",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/assignment",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/assignment",
    seedPath: "/api/v1/admin/users/<int:user_id>/assignment",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/assignment",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/admin/users/:userId/assignment",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/assignment",
    seedPath: "/api/v1/admin/users/<int:user_id>/assignment",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/admin/users/999999/assignment",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/password-reset",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/password-reset",
    seedPath: "/api/v1/admin/users/<int:user_id>/password-reset",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/password-reset",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/disable",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/disable",
    seedPath: "/api/v1/admin/users/<int:user_id>/disable",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/disable",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/enable",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/enable",
    seedPath: "/api/v1/admin/users/<int:user_id>/enable",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/enable",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/:userId/invite",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>/invite",
    seedPath: "/api/v1/admin/users/<int:user_id>/invite",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "POST",
      path: "/api/v1/admin/users/999999/invite",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/admin/users/invite",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/invite",
    seedPath: "/api/v1/admin/users/invite",
    routeFamily: "api_v1_admin",
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/admin/users/:userId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/admin/users/<int:user_id>",
    seedPath: "/api/v1/admin/users/<int:user_id>",
    routeFamily: "api_v1_admin",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/admin/users/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "admin_user_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/me/view-as",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/view-as",
    seedPath: "/api/v1/me/view-as",
    routeFamily: "api_v1",
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/me/view-as",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/view-as",
    seedPath: "/api/v1/me/view-as",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/create",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/create",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/create",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/characters/create",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/create",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/create",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/create",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/characters/create",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/advanced-editor",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/advanced-editor",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/advanced-editor",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/advanced-editor",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/retraining",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/retraining",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/retraining",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/retraining",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/level-up",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/level-up",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/level-up",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/level-up",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/characters/:characterSlug/progression-repair",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/progression-repair",
    seedPath: "/api/v1/campaigns/<campaign_slug>/characters/<character_slug>/progression-repair",
    routeFamily: "api_v1_characters",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/characters/missing-character/progression-repair",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
];

export const ROUTES = {
  healthz: IMPLEMENTED_ROUTES[0].honoPath,
  campaignDetail: IMPLEMENTED_ROUTES[1].honoPath,
  wikiHome: IMPLEMENTED_ROUTES[2].honoPath,
  wikiSection: IMPLEMENTED_ROUTES[3].honoPath,
  wikiPage: IMPLEMENTED_ROUTES[4].honoPath,
  sessionState: IMPLEMENTED_ROUTES[5].honoPath,
  sessionArticleSourceSearch: IMPLEMENTED_ROUTES[6].honoPath,
  campaignHelp: IMPLEMENTED_ROUTES[7].honoPath,
  campaignConfig: IMPLEMENTED_ROUTES[8].honoPath,
  contentPages: IMPLEMENTED_ROUTES[9].honoPath,
  contentAssets: IMPLEMENTED_ROUTES[10].honoPath,
  contentAsset: IMPLEMENTED_ROUTES[11].honoPath,
  contentPage: IMPLEMENTED_ROUTES[12].honoPath,
  contentCharacters: IMPLEMENTED_ROUTES[13].honoPath,
  contentCharacter: IMPLEMENTED_ROUTES[14].honoPath,
  systemsIndex: IMPLEMENTED_ROUTES[15].honoPath,
  systemsSearch: IMPLEMENTED_ROUTES[16].honoPath,
  systemsSources: IMPLEMENTED_ROUTES[17].honoPath,
  systemsSourceDetail: IMPLEMENTED_ROUTES[18].honoPath,
  systemsSourceCategory: IMPLEMENTED_ROUTES[19].honoPath,
  systemsEntryDetail: IMPLEMENTED_ROUTES[20].honoPath,
  combatSystemsMonsterSearch: IMPLEMENTED_ROUTES[21].honoPath,
  combatState: IMPLEMENTED_ROUTES[22].honoPath,
  combatLiveState: IMPLEMENTED_ROUTES[23].honoPath,
  campaignList: IMPLEMENTED_ROUTES[24].honoPath,
  appState: IMPLEMENTED_ROUTES[25].honoPath,
  systemsImportRuns: IMPLEMENTED_ROUTES[26].honoPath,
  systemsImportRun: IMPLEMENTED_ROUTES[27].honoPath,
  sessionArticleImage: IMPLEMENTED_ROUTES[28].honoPath,
  sessionLogDetail: IMPLEMENTED_ROUTES[29].honoPath,
  me: IMPLEMENTED_ROUTES[30].honoPath,
  meSettings: IMPLEMENTED_ROUTES[31].honoPath,
  meSettingsUpdate: IMPLEMENTED_ROUTES[32].honoPath,
  campaignControl: IMPLEMENTED_ROUTES[33].honoPath,
  campaignControlVisibility: IMPLEMENTED_ROUTES[34].honoPath,
  sessionMessageCreate: IMPLEMENTED_ROUTES[35].honoPath,
  sessionStart: IMPLEMENTED_ROUTES[36].honoPath,
  sessionClose: IMPLEMENTED_ROUTES[37].honoPath,
  sessionArticleCreate: IMPLEMENTED_ROUTES[38].honoPath,
  sessionArticleUpdate: IMPLEMENTED_ROUTES[39].honoPath,
  sessionArticleReveal: IMPLEMENTED_ROUTES[40].honoPath,
  sessionArticleDelete: IMPLEMENTED_ROUTES[41].honoPath,
  sessionArticlesRevealedClear: IMPLEMENTED_ROUTES[42].honoPath,
  sessionLogDelete: IMPLEMENTED_ROUTES[43].honoPath,
  campaignConfigUpdate: IMPLEMENTED_ROUTES[44].honoPath,
  contentAssetUpdate: IMPLEMENTED_ROUTES[45].honoPath,
  contentAssetDelete: IMPLEMENTED_ROUTES[46].honoPath,
  contentPageUpdate: IMPLEMENTED_ROUTES[47].honoPath,
  contentPageDelete: IMPLEMENTED_ROUTES[48].honoPath,
  contentCharacterUpdate: IMPLEMENTED_ROUTES[49].honoPath,
  contentCharacterDelete: IMPLEMENTED_ROUTES[50].honoPath,
  dmContentState: IMPLEMENTED_ROUTES[51].honoPath,
  dmContentStatblockCreate: IMPLEMENTED_ROUTES[52].honoPath,
  dmContentStatblockUpdate: IMPLEMENTED_ROUTES[53].honoPath,
  dmContentStatblockDelete: IMPLEMENTED_ROUTES[54].honoPath,
  dmContentConditionCreate: IMPLEMENTED_ROUTES[55].honoPath,
  dmContentConditionUpdate: IMPLEMENTED_ROUTES[56].honoPath,
  dmContentConditionDelete: IMPLEMENTED_ROUTES[57].honoPath,
  combatSetCurrent: IMPLEMENTED_ROUTES[58].honoPath,
  combatAdvanceTurn: IMPLEMENTED_ROUTES[59].honoPath,
  combatClear: IMPLEMENTED_ROUTES[60].honoPath,
  combatPlayerCombatants: IMPLEMENTED_ROUTES[61].honoPath,
  combatNpcCombatants: IMPLEMENTED_ROUTES[62].honoPath,
  combatStatblockCombatants: IMPLEMENTED_ROUTES[63].honoPath,
  combatSystemsMonsters: IMPLEMENTED_ROUTES[64].honoPath,
  combatCombatantTurn: IMPLEMENTED_ROUTES[65].honoPath,
  combatCombatantVitals: IMPLEMENTED_ROUTES[66].honoPath,
  combatCombatantResources: IMPLEMENTED_ROUTES[67].honoPath,
  combatCombatantNpcResources: IMPLEMENTED_ROUTES[68].honoPath,
  combatCombatantConditions: IMPLEMENTED_ROUTES[69].honoPath,
  combatCondition: IMPLEMENTED_ROUTES[70].honoPath,
  combatCombatant: IMPLEMENTED_ROUTES[71].honoPath,
  combatCombatantPlayerDetailVisibility: IMPLEMENTED_ROUTES[72].honoPath,
  combatConditionUpdate: IMPLEMENTED_ROUTES[73].honoPath,
  characterSessionVitals: IMPLEMENTED_ROUTES[74].honoPath,
  characterSessionResource: IMPLEMENTED_ROUTES[75].honoPath,
  characterSessionSpellSlots: IMPLEMENTED_ROUTES[76].honoPath,
  characterSessionInventory: IMPLEMENTED_ROUTES[77].honoPath,
  characterSessionXianxiaActiveState: IMPLEMENTED_ROUTES[78].honoPath,
  characterSessionCurrency: IMPLEMENTED_ROUTES[79].honoPath,
  characterSessionNotes: IMPLEMENTED_ROUTES[80].honoPath,
  characterSessionPersonal: IMPLEMENTED_ROUTES[81].honoPath,
  characterRestPreview: IMPLEMENTED_ROUTES[82].honoPath,
  characterSessionRest: IMPLEMENTED_ROUTES[83].honoPath,
  characterSessionFeatureState: IMPLEMENTED_ROUTES[84].honoPath,
  characterSessionXianxiaInventoryEquipped: IMPLEMENTED_ROUTES[85].honoPath,
  characterSessionXianxiaInventoryAdd: IMPLEMENTED_ROUTES[86].honoPath,
  characterSessionXianxiaInventoryRemove: IMPLEMENTED_ROUTES[87].honoPath,
  characterSessionXianxiaInventoryItem: IMPLEMENTED_ROUTES[88].honoPath,
  characterSessionEquipment: IMPLEMENTED_ROUTES[89].honoPath,
  characterSessionArtificerInfusions: IMPLEMENTED_ROUTES[90].honoPath,
  characterPortraitUpdate: IMPLEMENTED_ROUTES[91].honoPath,
  characterPortraitDelete: IMPLEMENTED_ROUTES[92].honoPath,
  characterSessionXianxiaDaoImmolatingUseRequests: IMPLEMENTED_ROUTES[93].honoPath,
  characterSessionXianxiaDaoImmolatingUseRecords: IMPLEMENTED_ROUTES[94].honoPath,
  characterControlsAssignment: IMPLEMENTED_ROUTES[95].honoPath,
  characterControlsDelete: IMPLEMENTED_ROUTES[97].honoPath,
  characterRoster: IMPLEMENTED_ROUTES[98].honoPath,
  characterDetail: IMPLEMENTED_ROUTES[99].honoPath,
  characterXianxiaManualImportContext: IMPLEMENTED_ROUTES[100].honoPath,
  characterXianxiaManualImport: IMPLEMENTED_ROUTES[101].honoPath,
  dmContentSystems: IMPLEMENTED_ROUTES[102].honoPath,
  systemsEntryOverrideUpdate: IMPLEMENTED_ROUTES[104].honoPath,
  systemsCustomEntries: IMPLEMENTED_ROUTES[105].honoPath,
  systemsCustomEntry: IMPLEMENTED_ROUTES[106].honoPath,
  systemsCustomEntryArchive: IMPLEMENTED_ROUTES[107].honoPath,
  systemsCustomEntryRestore: IMPLEMENTED_ROUTES[108].honoPath,
  systemsItemMechanicsImport: IMPLEMENTED_ROUTES[109].honoPath,
  systemsDnd5eImport: IMPLEMENTED_ROUTES[110].honoPath,
  adminDashboard: IMPLEMENTED_ROUTES[111].honoPath,
  adminUser: IMPLEMENTED_ROUTES[112].honoPath,
  characterSheetEdit: IMPLEMENTED_ROUTES[113].honoPath,
  adminUserMembership: IMPLEMENTED_ROUTES[114].honoPath,
  adminUserMembershipRemove: IMPLEMENTED_ROUTES[115].honoPath,
  adminUserAssignment: IMPLEMENTED_ROUTES[116].honoPath,
  adminUserAssignmentRemove: IMPLEMENTED_ROUTES[117].honoPath,
  adminUserPasswordReset: IMPLEMENTED_ROUTES[118].honoPath,
  adminUserDisable: IMPLEMENTED_ROUTES[119].honoPath,
  adminUserEnable: IMPLEMENTED_ROUTES[120].honoPath,
  adminUserInvite: IMPLEMENTED_ROUTES[121].honoPath,
  adminCreateInvite: IMPLEMENTED_ROUTES[122].honoPath,
  adminUserDelete: IMPLEMENTED_ROUTES[123].honoPath,
  meViewAsUpdate: IMPLEMENTED_ROUTES[124].honoPath,
  meViewAsClear: IMPLEMENTED_ROUTES[125].honoPath,
  characterCreateContext: IMPLEMENTED_ROUTES[126].honoPath,
  characterCreate: IMPLEMENTED_ROUTES[127].honoPath,
  characterAdvancedEditor: IMPLEMENTED_ROUTES[128].honoPath,
  characterRetraining: IMPLEMENTED_ROUTES[129].honoPath,
  characterLevelUp: IMPLEMENTED_ROUTES[130].honoPath,
  characterProgressionRepair: IMPLEMENTED_ROUTES[131].honoPath,
} as const;
