export type ImplementedRouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ImplementedRoute {
  method: ImplementedRouteMethod;
  honoPath: string;
  snapshotFamily: "api_v1" | "flask";
  snapshotPath: string;
  seedPath: string;
  routeFamily: string;
  missingResource?: {
    method: ImplementedRouteMethod;
    path: string;
    status: number;
    contentType: string;
    errorCode: string;
  };
}

export const IMPLEMENTED_ROUTES: ImplementedRoute[] = [
  {
    method: "GET",
    honoPath: "/healthz",
    snapshotFamily: "flask",
    snapshotPath: "/healthz",
    seedPath: "/healthz",
    routeFamily: "ops",
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/wiki",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki/sections/:sectionSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki/sections/<section_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki/sections/<section_slug>",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/wiki/sections/definitely-not-a-section",
      status: 404,
      contentType: "application/json",
      errorCode: "wiki_section_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/wiki/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/wiki/pages/<path:page_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/wiki/pages/<path:page_slug>",
    routeFamily: "api_v1_wiki",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/wiki/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "wiki_page_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/article-sources/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/article-sources/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/article-sources/search",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/article-sources/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/help",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/help",
    seedPath: "/api/v1/campaigns/<campaign_slug>/help",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/help",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/config",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/config",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/pages",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/assets",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/assets/definitely-not-an-asset.png",
      status: 404,
      contentType: "application/json",
      errorCode: "content_asset_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "content_page_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/characters",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/content/characters/missing-character",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/search",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/systems/sources",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources/:sourceId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/sources/NOPE",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_source_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/sources/:sourceId/types/:entryType",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>/types/<entry_type>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/sources/<source_id>/types/<entry_type>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/sources/PHB/types/definitely-not-a-type",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_source_category_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/systems/entries/:entrySlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/systems/entries/<entry_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/systems/entries/<entry_slug>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/systems/entries/definitely-not-an-entry",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_entry_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/systems-monsters/search",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters/search",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/systems-monsters/search",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/systems-monsters/search",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/combat/live-state",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/combat/live-state",
    seedPath: "/api/v1/campaigns/<campaign_slug>/combat/live-state",
    routeFamily: "api_v1_combat",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/combat/live-state",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns",
    seedPath: "/api/v1/campaigns",
    routeFamily: "api_v1_campaigns",
  },
  {
    method: "GET",
    honoPath: "/api/v1/app",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/app",
    seedPath: "/api/v1/app",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/systems/import-runs",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/systems/import-runs",
    seedPath: "/api/v1/systems/import-runs",
    routeFamily: "api_v1_systems",
  },
  {
    method: "GET",
    honoPath: "/api/v1/systems/import-runs/:importRunId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/systems/import-runs/<int:import_run_id>",
    seedPath: "/api/v1/systems/import-runs/<int:import_run_id>",
    routeFamily: "api_v1_systems",
    missingResource: {
      method: "GET",
      path: "/api/v1/systems/import-runs/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "systems_import_run_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId/image",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/image",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/image",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999/image",
      status: 404,
      contentType: "application/json",
      errorCode: "session_article_image_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/logs/:sessionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/linden-pass/session/logs/999999",
      status: 404,
      contentType: "application/json",
      errorCode: "session_log_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/me",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me",
    seedPath: "/api/v1/me",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/me/settings",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/settings",
    seedPath: "/api/v1/me/settings",
    routeFamily: "api_v1",
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/me/settings",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/me/settings",
    seedPath: "/api/v1/me/settings",
    routeFamily: "api_v1",
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/control",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/control",
    seedPath: "/api/v1/campaigns/<campaign_slug>/control",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/control",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/control/visibility",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/control/visibility",
    seedPath: "/api/v1/campaigns/<campaign_slug>/control/visibility",
    routeFamily: "api_v1_campaigns",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/definitely-not-a-campaign/control/visibility",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/messages",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/messages",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/messages",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/messages",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/start",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/start",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/start",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/start",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/close",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/close",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/close",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/close",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/articles",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId/reveal",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/reveal",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>/reveal",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999/reveal",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/:articleId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/<int:article_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/session/articles/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/articles/revealed",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/articles/revealed",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/articles/revealed",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/definitely-not-a-campaign/session/articles/revealed",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/session/logs/:sessionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/session/logs/<int:session_id>",
    routeFamily: "api_v1_session",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/session/logs/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "PATCH",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/config",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/config",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PATCH",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/config",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/assets/notes/api-sigil.txt",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/assets/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/assets/<path:asset_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/assets/definitely-not-an-asset.png",
      status: 404,
      contentType: "application/json",
      errorCode: "content_asset_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/pages/notes/api-field-report",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/pages/*",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/pages/<path:page_ref>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/pages/definitely-not-a-page",
      status: 404,
      contentType: "application/json",
      errorCode: "content_page_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/definitely-not-a-campaign/content/characters/api-scout",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/content/characters/:characterSlug",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/content/characters/<character_slug>",
    routeFamily: "api_v1_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/content/characters/missing-character",
      status: 404,
      contentType: "application/json",
      errorCode: "content_character_not_found",
    },
  },
  {
    method: "GET",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "GET",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content/statblocks",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks/:statblockId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/dm-content/statblocks/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/statblocks/:statblockId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/statblocks/<int:statblock_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/dm-content/statblocks/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "POST",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "POST",
      path: "/api/v1/campaigns/definitely-not-a-campaign/dm-content/conditions",
      status: 404,
      contentType: "application/json",
      errorCode: "campaign_not_found",
    },
  },
  {
    method: "PUT",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions/:conditionDefinitionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "PUT",
      path: "/api/v1/campaigns/linden-pass/dm-content/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
  {
    method: "DELETE",
    honoPath: "/api/v1/campaigns/:campaignSlug/dm-content/conditions/:conditionDefinitionId",
    snapshotFamily: "api_v1",
    snapshotPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    seedPath: "/api/v1/campaigns/<campaign_slug>/dm-content/conditions/<int:condition_definition_id>",
    routeFamily: "api_v1_dm_content",
    missingResource: {
      method: "DELETE",
      path: "/api/v1/campaigns/linden-pass/dm-content/conditions/999999",
      status: 400,
      contentType: "application/json",
      errorCode: "validation_error",
    },
  },
];

export const ROUTES = {
  healthz: IMPLEMENTED_ROUTES[0].honoPath,
  campaignDetail: IMPLEMENTED_ROUTES[1].honoPath,
  wikiHome: IMPLEMENTED_ROUTES[2].honoPath,
  wikiSection: IMPLEMENTED_ROUTES[3].honoPath,
  wikiPage: IMPLEMENTED_ROUTES[4].honoPath,
  sessionState: IMPLEMENTED_ROUTES[5].honoPath,
  sessionArticleSourceSearch: IMPLEMENTED_ROUTES[6].honoPath,
  campaignHelp: IMPLEMENTED_ROUTES[7].honoPath,
  campaignConfig: IMPLEMENTED_ROUTES[8].honoPath,
  contentPages: IMPLEMENTED_ROUTES[9].honoPath,
  contentAssets: IMPLEMENTED_ROUTES[10].honoPath,
  contentAsset: IMPLEMENTED_ROUTES[11].honoPath,
  contentPage: IMPLEMENTED_ROUTES[12].honoPath,
  contentCharacters: IMPLEMENTED_ROUTES[13].honoPath,
  contentCharacter: IMPLEMENTED_ROUTES[14].honoPath,
  systemsIndex: IMPLEMENTED_ROUTES[15].honoPath,
  systemsSearch: IMPLEMENTED_ROUTES[16].honoPath,
  systemsSources: IMPLEMENTED_ROUTES[17].honoPath,
  systemsSourceDetail: IMPLEMENTED_ROUTES[18].honoPath,
  systemsSourceCategory: IMPLEMENTED_ROUTES[19].honoPath,
  systemsEntryDetail: IMPLEMENTED_ROUTES[20].honoPath,
  combatSystemsMonsterSearch: IMPLEMENTED_ROUTES[21].honoPath,
  combatState: IMPLEMENTED_ROUTES[22].honoPath,
  combatLiveState: IMPLEMENTED_ROUTES[23].honoPath,
  campaignList: IMPLEMENTED_ROUTES[24].honoPath,
  appState: IMPLEMENTED_ROUTES[25].honoPath,
  systemsImportRuns: IMPLEMENTED_ROUTES[26].honoPath,
  systemsImportRun: IMPLEMENTED_ROUTES[27].honoPath,
  sessionArticleImage: IMPLEMENTED_ROUTES[28].honoPath,
  sessionLogDetail: IMPLEMENTED_ROUTES[29].honoPath,
  me: IMPLEMENTED_ROUTES[30].honoPath,
  meSettings: IMPLEMENTED_ROUTES[31].honoPath,
  meSettingsUpdate: IMPLEMENTED_ROUTES[32].honoPath,
  campaignControl: IMPLEMENTED_ROUTES[33].honoPath,
  campaignControlVisibility: IMPLEMENTED_ROUTES[34].honoPath,
  sessionMessageCreate: IMPLEMENTED_ROUTES[35].honoPath,
  sessionStart: IMPLEMENTED_ROUTES[36].honoPath,
  sessionClose: IMPLEMENTED_ROUTES[37].honoPath,
  sessionArticleCreate: IMPLEMENTED_ROUTES[38].honoPath,
  sessionArticleUpdate: IMPLEMENTED_ROUTES[39].honoPath,
  sessionArticleReveal: IMPLEMENTED_ROUTES[40].honoPath,
  sessionArticleDelete: IMPLEMENTED_ROUTES[41].honoPath,
  sessionArticlesRevealedClear: IMPLEMENTED_ROUTES[42].honoPath,
  sessionLogDelete: IMPLEMENTED_ROUTES[43].honoPath,
  campaignConfigUpdate: IMPLEMENTED_ROUTES[44].honoPath,
  contentAssetUpdate: IMPLEMENTED_ROUTES[45].honoPath,
  contentAssetDelete: IMPLEMENTED_ROUTES[46].honoPath,
  contentPageUpdate: IMPLEMENTED_ROUTES[47].honoPath,
  contentPageDelete: IMPLEMENTED_ROUTES[48].honoPath,
  contentCharacterUpdate: IMPLEMENTED_ROUTES[49].honoPath,
  contentCharacterDelete: IMPLEMENTED_ROUTES[50].honoPath,
  dmContentState: IMPLEMENTED_ROUTES[51].honoPath,
  dmContentStatblockCreate: IMPLEMENTED_ROUTES[52].honoPath,
  dmContentStatblockUpdate: IMPLEMENTED_ROUTES[53].honoPath,
  dmContentStatblockDelete: IMPLEMENTED_ROUTES[54].honoPath,
  dmContentConditionCreate: IMPLEMENTED_ROUTES[55].honoPath,
  dmContentConditionUpdate: IMPLEMENTED_ROUTES[56].honoPath,
  dmContentConditionDelete: IMPLEMENTED_ROUTES[57].honoPath,
} as const;
