/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CampaignsCampaignSlugIndexRouteImport } from './routes/campaigns/$campaignSlug/index'
import { Route as CampaignsCampaignSlugSessionRouteImport } from './routes/campaigns/$campaignSlug/session'
import { Route as CampaignsCampaignSlugHelpRouteImport } from './routes/campaigns/$campaignSlug/help'
import { Route as CampaignsCampaignSlugDmContentRouteImport } from './routes/campaigns/$campaignSlug/dm-content'
import { Route as CampaignsCampaignSlugControlRouteImport } from './routes/campaigns/$campaignSlug/control'
import { Route as CampaignsCampaignSlugCombatRouteImport } from './routes/campaigns/$campaignSlug/combat'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as CampaignsCampaignSlugSystemsIndexRouteImport } from './routes/campaigns/$campaignSlug/systems/index'
import { Route as CampaignsCampaignSlugCharactersIndexRouteImport } from './routes/campaigns/$campaignSlug/characters/index'
import { Route as CampaignsCampaignSlugSectionsSectionSlugRouteImport } from './routes/campaigns/$campaignSlug/sections/$sectionSlug'
import { Route as CampaignsCampaignSlugPagesSplatRouteImport } from './routes/campaigns/$campaignSlug/pages/$'
import { Route as CampaignsCampaignSlugCharactersNewRouteImport } from './routes/campaigns/$campaignSlug/characters/new'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugIndexRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/index'
import { Route as CampaignsCampaignSlugSystemsEntriesEntrySlugRouteImport } from './routes/campaigns/$campaignSlug/systems/entries/$entrySlug'
import { Route as CampaignsCampaignSlugCharactersImportXianxiaManualRouteImport } from './routes/campaigns/$campaignSlug/characters/import/xianxia-manual'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugRetrainingRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/retraining'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugLevelUpRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/level-up'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugEditRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/edit'
import { Route as CampaignsCampaignSlugCharactersCharacterSlugCultivationRouteImport } from './routes/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
import { Route as CampaignsCampaignSlugSystemsSourcesSourceIdIndexRouteImport } from './routes/campaigns/$campaignSlug/systems/sources/$sourceId/index'
import { Route as CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRouteImport } from './routes/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignSlugIndexRoute =
  CampaignsCampaignSlugIndexRouteImport.update({
    id: '/campaigns/$campaignSlug/',
    path: '/campaigns/$campaignSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugSessionRoute =
  CampaignsCampaignSlugSessionRouteImport.update({
    id: '/campaigns/$campaignSlug/session',
    path: '/campaigns/$campaignSlug/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugHelpRoute =
  CampaignsCampaignSlugHelpRouteImport.update({
    id: '/campaigns/$campaignSlug/help',
    path: '/campaigns/$campaignSlug/help',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugDmContentRoute =
  CampaignsCampaignSlugDmContentRouteImport.update({
    id: '/campaigns/$campaignSlug/dm-content',
    path: '/campaigns/$campaignSlug/dm-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugControlRoute =
  CampaignsCampaignSlugControlRouteImport.update({
    id: '/campaigns/$campaignSlug/control',
    path: '/campaigns/$campaignSlug/control',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCombatRoute =
  CampaignsCampaignSlugCombatRouteImport.update({
    id: '/campaigns/$campaignSlug/combat',
    path: '/campaigns/$campaignSlug/combat',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignSlugSystemsIndexRoute =
  CampaignsCampaignSlugSystemsIndexRouteImport.update({
    id: '/campaigns/$campaignSlug/systems/',
    path: '/campaigns/$campaignSlug/systems/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersIndexRoute =
  CampaignsCampaignSlugCharactersIndexRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/',
    path: '/campaigns/$campaignSlug/characters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugSectionsSectionSlugRoute =
  CampaignsCampaignSlugSectionsSectionSlugRouteImport.update({
    id: '/campaigns/$campaignSlug/sections/$sectionSlug',
    path: '/campaigns/$campaignSlug/sections/$sectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugPagesSplatRoute =
  CampaignsCampaignSlugPagesSplatRouteImport.update({
    id: '/campaigns/$campaignSlug/pages/$',
    path: '/campaigns/$campaignSlug/pages/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersNewRoute =
  CampaignsCampaignSlugCharactersNewRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/new',
    path: '/campaigns/$campaignSlug/characters/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersCharacterSlugIndexRoute =
  CampaignsCampaignSlugCharactersCharacterSlugIndexRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/$characterSlug/',
    path: '/campaigns/$campaignSlug/characters/$characterSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugSystemsEntriesEntrySlugRoute =
  CampaignsCampaignSlugSystemsEntriesEntrySlugRouteImport.update({
    id: '/campaigns/$campaignSlug/systems/entries/$entrySlug',
    path: '/campaigns/$campaignSlug/systems/entries/$entrySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersImportXianxiaManualRoute =
  CampaignsCampaignSlugCharactersImportXianxiaManualRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/import/xianxia-manual',
    path: '/campaigns/$campaignSlug/characters/import/xianxia-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute =
  CampaignsCampaignSlugCharactersCharacterSlugRetrainingRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/$characterSlug/retraining',
    path: '/campaigns/$campaignSlug/characters/$characterSlug/retraining',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute =
  CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRouteImport.update(
    {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair',
      path: '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute =
  CampaignsCampaignSlugCharactersCharacterSlugLevelUpRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/$characterSlug/level-up',
    path: '/campaigns/$campaignSlug/characters/$characterSlug/level-up',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersCharacterSlugEditRoute =
  CampaignsCampaignSlugCharactersCharacterSlugEditRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/$characterSlug/edit',
    path: '/campaigns/$campaignSlug/characters/$characterSlug/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute =
  CampaignsCampaignSlugCharactersCharacterSlugCultivationRouteImport.update({
    id: '/campaigns/$campaignSlug/characters/$characterSlug/cultivation',
    path: '/campaigns/$campaignSlug/characters/$characterSlug/cultivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute =
  CampaignsCampaignSlugSystemsSourcesSourceIdIndexRouteImport.update({
    id: '/campaigns/$campaignSlug/systems/sources/$sourceId/',
    path: '/campaigns/$campaignSlug/systems/sources/$sourceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute =
  CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRouteImport.update({
    id: '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType',
    path: '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/campaigns/$campaignSlug/combat': typeof CampaignsCampaignSlugCombatRoute
  '/campaigns/$campaignSlug/control': typeof CampaignsCampaignSlugControlRoute
  '/campaigns/$campaignSlug/dm-content': typeof CampaignsCampaignSlugDmContentRoute
  '/campaigns/$campaignSlug/help': typeof CampaignsCampaignSlugHelpRoute
  '/campaigns/$campaignSlug/session': typeof CampaignsCampaignSlugSessionRoute
  '/campaigns/$campaignSlug/': typeof CampaignsCampaignSlugIndexRoute
  '/campaigns/$campaignSlug/characters/new': typeof CampaignsCampaignSlugCharactersNewRoute
  '/campaigns/$campaignSlug/pages/$': typeof CampaignsCampaignSlugPagesSplatRoute
  '/campaigns/$campaignSlug/sections/$sectionSlug': typeof CampaignsCampaignSlugSectionsSectionSlugRoute
  '/campaigns/$campaignSlug/characters/': typeof CampaignsCampaignSlugCharactersIndexRoute
  '/campaigns/$campaignSlug/systems/': typeof CampaignsCampaignSlugSystemsIndexRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/cultivation': typeof CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/edit': typeof CampaignsCampaignSlugCharactersCharacterSlugEditRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/level-up': typeof CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair': typeof CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/retraining': typeof CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute
  '/campaigns/$campaignSlug/characters/import/xianxia-manual': typeof CampaignsCampaignSlugCharactersImportXianxiaManualRoute
  '/campaigns/$campaignSlug/systems/entries/$entrySlug': typeof CampaignsCampaignSlugSystemsEntriesEntrySlugRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/': typeof CampaignsCampaignSlugCharactersCharacterSlugIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId/': typeof CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType': typeof CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/campaigns/$campaignSlug/combat': typeof CampaignsCampaignSlugCombatRoute
  '/campaigns/$campaignSlug/control': typeof CampaignsCampaignSlugControlRoute
  '/campaigns/$campaignSlug/dm-content': typeof CampaignsCampaignSlugDmContentRoute
  '/campaigns/$campaignSlug/help': typeof CampaignsCampaignSlugHelpRoute
  '/campaigns/$campaignSlug/session': typeof CampaignsCampaignSlugSessionRoute
  '/campaigns/$campaignSlug': typeof CampaignsCampaignSlugIndexRoute
  '/campaigns/$campaignSlug/characters/new': typeof CampaignsCampaignSlugCharactersNewRoute
  '/campaigns/$campaignSlug/pages/$': typeof CampaignsCampaignSlugPagesSplatRoute
  '/campaigns/$campaignSlug/sections/$sectionSlug': typeof CampaignsCampaignSlugSectionsSectionSlugRoute
  '/campaigns/$campaignSlug/characters': typeof CampaignsCampaignSlugCharactersIndexRoute
  '/campaigns/$campaignSlug/systems': typeof CampaignsCampaignSlugSystemsIndexRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/cultivation': typeof CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/edit': typeof CampaignsCampaignSlugCharactersCharacterSlugEditRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/level-up': typeof CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair': typeof CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/retraining': typeof CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute
  '/campaigns/$campaignSlug/characters/import/xianxia-manual': typeof CampaignsCampaignSlugCharactersImportXianxiaManualRoute
  '/campaigns/$campaignSlug/systems/entries/$entrySlug': typeof CampaignsCampaignSlugSystemsEntriesEntrySlugRoute
  '/campaigns/$campaignSlug/characters/$characterSlug': typeof CampaignsCampaignSlugCharactersCharacterSlugIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId': typeof CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType': typeof CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/campaigns/$campaignSlug/combat': typeof CampaignsCampaignSlugCombatRoute
  '/campaigns/$campaignSlug/control': typeof CampaignsCampaignSlugControlRoute
  '/campaigns/$campaignSlug/dm-content': typeof CampaignsCampaignSlugDmContentRoute
  '/campaigns/$campaignSlug/help': typeof CampaignsCampaignSlugHelpRoute
  '/campaigns/$campaignSlug/session': typeof CampaignsCampaignSlugSessionRoute
  '/campaigns/$campaignSlug/': typeof CampaignsCampaignSlugIndexRoute
  '/campaigns/$campaignSlug/characters/new': typeof CampaignsCampaignSlugCharactersNewRoute
  '/campaigns/$campaignSlug/pages/$': typeof CampaignsCampaignSlugPagesSplatRoute
  '/campaigns/$campaignSlug/sections/$sectionSlug': typeof CampaignsCampaignSlugSectionsSectionSlugRoute
  '/campaigns/$campaignSlug/characters/': typeof CampaignsCampaignSlugCharactersIndexRoute
  '/campaigns/$campaignSlug/systems/': typeof CampaignsCampaignSlugSystemsIndexRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/cultivation': typeof CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/edit': typeof CampaignsCampaignSlugCharactersCharacterSlugEditRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/level-up': typeof CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair': typeof CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/retraining': typeof CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute
  '/campaigns/$campaignSlug/characters/import/xianxia-manual': typeof CampaignsCampaignSlugCharactersImportXianxiaManualRoute
  '/campaigns/$campaignSlug/systems/entries/$entrySlug': typeof CampaignsCampaignSlugSystemsEntriesEntrySlugRoute
  '/campaigns/$campaignSlug/characters/$characterSlug/': typeof CampaignsCampaignSlugCharactersCharacterSlugIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId/': typeof CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute
  '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType': typeof CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin/'
    | '/admin/users/$userId'
    | '/campaigns/$campaignSlug/combat'
    | '/campaigns/$campaignSlug/control'
    | '/campaigns/$campaignSlug/dm-content'
    | '/campaigns/$campaignSlug/help'
    | '/campaigns/$campaignSlug/session'
    | '/campaigns/$campaignSlug/'
    | '/campaigns/$campaignSlug/characters/new'
    | '/campaigns/$campaignSlug/pages/$'
    | '/campaigns/$campaignSlug/sections/$sectionSlug'
    | '/campaigns/$campaignSlug/characters/'
    | '/campaigns/$campaignSlug/systems/'
    | '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
    | '/campaigns/$campaignSlug/characters/$characterSlug/edit'
    | '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
    | '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
    | '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
    | '/campaigns/$campaignSlug/characters/import/xianxia-manual'
    | '/campaigns/$campaignSlug/systems/entries/$entrySlug'
    | '/campaigns/$campaignSlug/characters/$characterSlug/'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId/'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/admin/users/$userId'
    | '/campaigns/$campaignSlug/combat'
    | '/campaigns/$campaignSlug/control'
    | '/campaigns/$campaignSlug/dm-content'
    | '/campaigns/$campaignSlug/help'
    | '/campaigns/$campaignSlug/session'
    | '/campaigns/$campaignSlug'
    | '/campaigns/$campaignSlug/characters/new'
    | '/campaigns/$campaignSlug/pages/$'
    | '/campaigns/$campaignSlug/sections/$sectionSlug'
    | '/campaigns/$campaignSlug/characters'
    | '/campaigns/$campaignSlug/systems'
    | '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
    | '/campaigns/$campaignSlug/characters/$characterSlug/edit'
    | '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
    | '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
    | '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
    | '/campaigns/$campaignSlug/characters/import/xianxia-manual'
    | '/campaigns/$campaignSlug/systems/entries/$entrySlug'
    | '/campaigns/$campaignSlug/characters/$characterSlug'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin/'
    | '/admin/users/$userId'
    | '/campaigns/$campaignSlug/combat'
    | '/campaigns/$campaignSlug/control'
    | '/campaigns/$campaignSlug/dm-content'
    | '/campaigns/$campaignSlug/help'
    | '/campaigns/$campaignSlug/session'
    | '/campaigns/$campaignSlug/'
    | '/campaigns/$campaignSlug/characters/new'
    | '/campaigns/$campaignSlug/pages/$'
    | '/campaigns/$campaignSlug/sections/$sectionSlug'
    | '/campaigns/$campaignSlug/characters/'
    | '/campaigns/$campaignSlug/systems/'
    | '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
    | '/campaigns/$campaignSlug/characters/$characterSlug/edit'
    | '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
    | '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
    | '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
    | '/campaigns/$campaignSlug/characters/import/xianxia-manual'
    | '/campaigns/$campaignSlug/systems/entries/$entrySlug'
    | '/campaigns/$campaignSlug/characters/$characterSlug/'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId/'
    | '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  CampaignsCampaignSlugCombatRoute: typeof CampaignsCampaignSlugCombatRoute
  CampaignsCampaignSlugControlRoute: typeof CampaignsCampaignSlugControlRoute
  CampaignsCampaignSlugDmContentRoute: typeof CampaignsCampaignSlugDmContentRoute
  CampaignsCampaignSlugHelpRoute: typeof CampaignsCampaignSlugHelpRoute
  CampaignsCampaignSlugSessionRoute: typeof CampaignsCampaignSlugSessionRoute
  CampaignsCampaignSlugIndexRoute: typeof CampaignsCampaignSlugIndexRoute
  CampaignsCampaignSlugCharactersNewRoute: typeof CampaignsCampaignSlugCharactersNewRoute
  CampaignsCampaignSlugPagesSplatRoute: typeof CampaignsCampaignSlugPagesSplatRoute
  CampaignsCampaignSlugSectionsSectionSlugRoute: typeof CampaignsCampaignSlugSectionsSectionSlugRoute
  CampaignsCampaignSlugCharactersIndexRoute: typeof CampaignsCampaignSlugCharactersIndexRoute
  CampaignsCampaignSlugSystemsIndexRoute: typeof CampaignsCampaignSlugSystemsIndexRoute
  CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute
  CampaignsCampaignSlugCharactersCharacterSlugEditRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugEditRoute
  CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute
  CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute
  CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute
  CampaignsCampaignSlugCharactersImportXianxiaManualRoute: typeof CampaignsCampaignSlugCharactersImportXianxiaManualRoute
  CampaignsCampaignSlugSystemsEntriesEntrySlugRoute: typeof CampaignsCampaignSlugSystemsEntriesEntrySlugRoute
  CampaignsCampaignSlugCharactersCharacterSlugIndexRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugIndexRoute
  CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute: typeof CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute
  CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute: typeof CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/': {
      id: '/campaigns/$campaignSlug/'
      path: '/campaigns/$campaignSlug'
      fullPath: '/campaigns/$campaignSlug/'
      preLoaderRoute: typeof CampaignsCampaignSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/session': {
      id: '/campaigns/$campaignSlug/session'
      path: '/campaigns/$campaignSlug/session'
      fullPath: '/campaigns/$campaignSlug/session'
      preLoaderRoute: typeof CampaignsCampaignSlugSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/help': {
      id: '/campaigns/$campaignSlug/help'
      path: '/campaigns/$campaignSlug/help'
      fullPath: '/campaigns/$campaignSlug/help'
      preLoaderRoute: typeof CampaignsCampaignSlugHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/dm-content': {
      id: '/campaigns/$campaignSlug/dm-content'
      path: '/campaigns/$campaignSlug/dm-content'
      fullPath: '/campaigns/$campaignSlug/dm-content'
      preLoaderRoute: typeof CampaignsCampaignSlugDmContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/control': {
      id: '/campaigns/$campaignSlug/control'
      path: '/campaigns/$campaignSlug/control'
      fullPath: '/campaigns/$campaignSlug/control'
      preLoaderRoute: typeof CampaignsCampaignSlugControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/combat': {
      id: '/campaigns/$campaignSlug/combat'
      path: '/campaigns/$campaignSlug/combat'
      fullPath: '/campaigns/$campaignSlug/combat'
      preLoaderRoute: typeof CampaignsCampaignSlugCombatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/systems/': {
      id: '/campaigns/$campaignSlug/systems/'
      path: '/campaigns/$campaignSlug/systems'
      fullPath: '/campaigns/$campaignSlug/systems/'
      preLoaderRoute: typeof CampaignsCampaignSlugSystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/': {
      id: '/campaigns/$campaignSlug/characters/'
      path: '/campaigns/$campaignSlug/characters'
      fullPath: '/campaigns/$campaignSlug/characters/'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/sections/$sectionSlug': {
      id: '/campaigns/$campaignSlug/sections/$sectionSlug'
      path: '/campaigns/$campaignSlug/sections/$sectionSlug'
      fullPath: '/campaigns/$campaignSlug/sections/$sectionSlug'
      preLoaderRoute: typeof CampaignsCampaignSlugSectionsSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/pages/$': {
      id: '/campaigns/$campaignSlug/pages/$'
      path: '/campaigns/$campaignSlug/pages/$'
      fullPath: '/campaigns/$campaignSlug/pages/$'
      preLoaderRoute: typeof CampaignsCampaignSlugPagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/new': {
      id: '/campaigns/$campaignSlug/characters/new'
      path: '/campaigns/$campaignSlug/characters/new'
      fullPath: '/campaigns/$campaignSlug/characters/new'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/'
      path: '/campaigns/$campaignSlug/characters/$characterSlug'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/systems/entries/$entrySlug': {
      id: '/campaigns/$campaignSlug/systems/entries/$entrySlug'
      path: '/campaigns/$campaignSlug/systems/entries/$entrySlug'
      fullPath: '/campaigns/$campaignSlug/systems/entries/$entrySlug'
      preLoaderRoute: typeof CampaignsCampaignSlugSystemsEntriesEntrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/import/xianxia-manual': {
      id: '/campaigns/$campaignSlug/characters/import/xianxia-manual'
      path: '/campaigns/$campaignSlug/characters/import/xianxia-manual'
      fullPath: '/campaigns/$campaignSlug/characters/import/xianxia-manual'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersImportXianxiaManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/retraining': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
      path: '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/retraining'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugRetrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
      path: '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/progression-repair'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/level-up': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
      path: '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/level-up'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugLevelUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/edit': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/edit'
      path: '/campaigns/$campaignSlug/characters/$characterSlug/edit'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/edit'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/characters/$characterSlug/cultivation': {
      id: '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
      path: '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
      fullPath: '/campaigns/$campaignSlug/characters/$characterSlug/cultivation'
      preLoaderRoute: typeof CampaignsCampaignSlugCharactersCharacterSlugCultivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/systems/sources/$sourceId/': {
      id: '/campaigns/$campaignSlug/systems/sources/$sourceId/'
      path: '/campaigns/$campaignSlug/systems/sources/$sourceId'
      fullPath: '/campaigns/$campaignSlug/systems/sources/$sourceId/'
      preLoaderRoute: typeof CampaignsCampaignSlugSystemsSourcesSourceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType': {
      id: '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
      path: '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
      fullPath: '/campaigns/$campaignSlug/systems/sources/$sourceId/types/$entryType'
      preLoaderRoute: typeof CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  CampaignsCampaignSlugCombatRoute: CampaignsCampaignSlugCombatRoute,
  CampaignsCampaignSlugControlRoute: CampaignsCampaignSlugControlRoute,
  CampaignsCampaignSlugDmContentRoute: CampaignsCampaignSlugDmContentRoute,
  CampaignsCampaignSlugHelpRoute: CampaignsCampaignSlugHelpRoute,
  CampaignsCampaignSlugSessionRoute: CampaignsCampaignSlugSessionRoute,
  CampaignsCampaignSlugIndexRoute: CampaignsCampaignSlugIndexRoute,
  CampaignsCampaignSlugCharactersNewRoute:
    CampaignsCampaignSlugCharactersNewRoute,
  CampaignsCampaignSlugPagesSplatRoute: CampaignsCampaignSlugPagesSplatRoute,
  CampaignsCampaignSlugSectionsSectionSlugRoute:
    CampaignsCampaignSlugSectionsSectionSlugRoute,
  CampaignsCampaignSlugCharactersIndexRoute:
    CampaignsCampaignSlugCharactersIndexRoute,
  CampaignsCampaignSlugSystemsIndexRoute:
    CampaignsCampaignSlugSystemsIndexRoute,
  CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute:
    CampaignsCampaignSlugCharactersCharacterSlugCultivationRoute,
  CampaignsCampaignSlugCharactersCharacterSlugEditRoute:
    CampaignsCampaignSlugCharactersCharacterSlugEditRoute,
  CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute:
    CampaignsCampaignSlugCharactersCharacterSlugLevelUpRoute,
  CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute:
    CampaignsCampaignSlugCharactersCharacterSlugProgressionRepairRoute,
  CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute:
    CampaignsCampaignSlugCharactersCharacterSlugRetrainingRoute,
  CampaignsCampaignSlugCharactersImportXianxiaManualRoute:
    CampaignsCampaignSlugCharactersImportXianxiaManualRoute,
  CampaignsCampaignSlugSystemsEntriesEntrySlugRoute:
    CampaignsCampaignSlugSystemsEntriesEntrySlugRoute,
  CampaignsCampaignSlugCharactersCharacterSlugIndexRoute:
    CampaignsCampaignSlugCharactersCharacterSlugIndexRoute,
  CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute:
    CampaignsCampaignSlugSystemsSourcesSourceIdIndexRoute,
  CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute:
    CampaignsCampaignSlugSystemsSourcesSourceIdTypesEntryTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
